export const clinicInfo = {
  doctorName: 'Dr. Alexander Morgan',
  brandName: 'BrightSmile Advanced Dental Care',
  heroTitle: 'International Cosmetic and Implant Dentistry',
  tagline: 'Advanced dental care in downtown San Francisco with a calm, modern, and patient-first experience.',
  address: '245 Market Street, Suite 520, San Francisco, CA 94105, USA',
  city: 'San Francisco',
  region: 'California',
  postalCode: '94105',
  country: 'United States',
  phonePrimary: '+1 (415) 728-5934',
  phoneSecondary: '',
  phonePrimaryHref: 'tel:+14157285934',
  phoneSecondaryHref: '',
  whatsappNumber: '+14157285934',
  whatsappHref: 'https://wa.me/14157285934',
  email: 'alex.morgan.dentist@gmail.com',
  emailHref: 'mailto:alex.morgan.dentist@gmail.com',
  mapQuery: '245 Market Street Suite 520 San Francisco CA 94105',
  mapTitle: 'BrightSmile Advanced Dental Care - San Francisco',
  mapEmbedUrl:
    'https://www.google.com/maps?q=245%20Market%20Street%2C%20Suite%20520%2C%20San%20Francisco%2C%20CA%2094105&z=15&output=embed',
  hours: 'Mon-Fri 8:30 AM - 6:30 PM | Sat 9:00 AM - 3:00 PM | Sun Closed',
  workingHours: [
    'Monday - Friday: 8:30 AM - 6:30 PM',
    'Saturday: 9:00 AM - 3:00 PM',
    'Sunday: Closed',
  ],
  specializations: [
    'Cosmetic Dentistry',
    'Dental Implants',
    'Invisalign and Orthodontics',
    'Teeth Whitening',
    'Oral Surgery',
  ],
  education: [
    'Doctor of Dental Surgery (DDS) - University of California, San Francisco (UCSF)',
    'Advanced Implantology Certification - New York Institute of Dentistry',
  ],
  experience: '10+ years of experience in advanced dental care and cosmetic treatments.',
  languages: ['English', 'Spanish'],
  availableAppointments: [
    'Monday 10:00 AM',
    'Tuesday 2:30 PM',
    'Wednesday 11:30 AM',
    'Thursday 4:00 PM',
    'Friday 9:00 AM',
    'Saturday 12:30 PM',
  ],
};
